version: '3.8'

services:
  job-scraper:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - CHROME_MINIMAL_CONFIG=true
    volumes:
      - ./screenshots:/app/screenshots
      - /dev/shm:/dev/shm  # Shared memory for Chrome
    restart: "no"
    shm_size: 2g
    # Add memory limits for better container stability
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
 