version: '3.8'

services:
  job-scraper:
    build: .
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./screenshots:/app/screenshots
    restart: "no"
    shm_size: 2g
 