name: LinkedIn Job Scraper

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 */3 * * *' # Every 3 hours

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create environment file
        run: |
          cat > .env << EOF
          OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
          LINKEDIN_PASSWORD=${{ secrets.LINKEDIN_PASSWORD }}
          EOF

      - name: Create cookies file
        run: echo '${{ secrets.COOKIES_JSON }}' > cookies.json

      - name: Run job scraper
        run: |
          docker compose up --build --abort-on-container-exit
          
      - name: Cleanup
        if: always()
        run: |
          docker compose down --volumes --remove-orphans
          docker system prune -f 